name: BlueBridgeCore
main: de.mark225.bluebridge.core.BlueBridgeCore
version: ${gradleVersion}
authors: [ ${ contributors } ]
website: https://github.com/minecraft-gilde/BlueBridge
api-version: '1.21.11'
folia-supported: true
depend: [ "BlueMap" ]
